### ISSUE TITLE
Response Return

### ISSUE THREAD

**Issue by TarekJubaerS** [hizbul25/onnorokom-sms#1]
I would suggest to return response in array with the error code and message received from the API.

Example-
`try{`
           ` $value = $soapClient->__call($config['delivery_type'], $onnorokomArray);`

            `$arrResult = explode("||", $value->OneToOneResult);`
            
            `return $arrResult;`
            
        `}`
        `catch (\SoapFault $ex)`
        `{`
            `return [0 => '9999', 1 => $ex->getMessage()];`
            
        `}`

**Comment by hizbul25** [comment]
Thanks for your suggestion. You may create a pull request with your code.
