### ISSUE TITLE
setup isuue

### ISSUE THREAD

**Issue by abhijit503** [hizbul25/onnorokom-sms#3]
hello sir, i was found a issue in installing your laravel package.
after (php artisan vendor:publish) command run i paste this config/onnorokom.php, but it through a error msg ( [ERROR] Value "config/onnorokom.php" is invalid). i cant understood that.
can you help me?

**Comment by hizbul25** [comment]
Which laravel and php version you are using?

**Comment by hizbul25** [comment]
> hello sir, i was found a issue in installing your laravel package.
> after (php artisan vendor:publish) command run i paste this config/onnorokom.php, but it through a error msg ( [ERROR] Value "config/onnorokom.php" is invalid). i cant understood that.
> can you help me?

**Comment by hizbul25** [comment]
Which laravel and php version you are using?

**Comment by abhijit503** [comment]
sir laravel 8

**Comment by hizbul25** [comment]
@abhijit503 for your convenience, I've updated documents, please have a look https://github.com/hizbul25/onnorokom-sms#configuration and let me if it works.
